name: 'K8s object differ'
author: 'berquerant'
description: 'Compare manifests for each corresponding object'
inputs:
  left:
    description: 'Left manifest file'
    required: true
  right:
    description: 'Right manifest file'
    required: true
  fail-on-diff:
    description: 'Fail the action if a diff is detected'
    required: false
    default: 'false'
outputs:
  status:
    description: '0 if left = right, 1 if left != right, otherwise trouble'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.fail-on-diff }}
    - ${{ inputs.left }}
    - ${{ inputs.right }}
